# Generated by Django 3.2.9 on 2022-02-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_delete_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islamicarticle',
            name='article_meta',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='islamicarticle',
            name='bcontent',
            field=models.TextField(max_length=15000),
        ),
    ]
