# Generated by Django 3.2.9 on 2022-02-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islamoshop', '0007_alter_purchasinghistory_transactionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
